kind: pipeline
name: autobuild

steps:
- name: build
  image: gradle:7.4-jdk17
  commands:
  - gradle clean build
- name: retag
  image: alpine/git:latest
  environment:
    GITEA_KEY:
      from_secret: gitea_key
  commands:
  - "git tag -d dev-1.19 || true"
  - git tag dev-1.19 1.19.2
  - "git push -f https://drone:$GITEA_KEY@git.sleeping.town/unascribed/Yttr.git dev-1.19"
- name: release
  image: unascribed/drone-gitea-release
  settings:
    api_key:
      from_secret: gitea_key
    base_url: https://git.sleeping.town
    files:
      - build/libs/yttr-*.jar
    title: "[1.19] Dev Build"
    prerelease: true
    tag: dev-1.19
    note: CHANGELOG.md
    allow_edit: true

trigger:
    branch:
    - "1.19.2"
    event:
    - push
