kind: pipeline
name: autobuild

steps:
- name: restore-cache
  image: meltwater/drone-cache
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: s3id
    AWS_SECRET_ACCESS_KEY:
      from_secret: s3key
  pull: true
  settings:
    restore: true
    path-style: true
    bucket:
      from_secret: s3bucket
    region:
      from_secret: s3region
    endpoint:
      from_secret: s3url
    mount:
      - '.gradle'
      - '/root/.gradle'
- name: build
  image: gradle:7.4-jdk17
  commands:
  - gradle clean build
- name: retag
  image: alpine/git:latest
  environment:
    GITEA_KEY:
      from_secret: gitea_key
  commands:
  - "git tag -d dev-1.18 || true"
  - git tag dev-1.18 1.18.2
  - "git push -f https://drone:$GITEA_KEY@git.sleeping.town/unascribed/Yttr.git dev-1.18"
- name: release
  image: unascribed/drone-gitea-release
  settings:
    api_key:
      from_secret: gitea_key
    base_url: https://git.sleeping.town
    files:
      - build/libs/yttr-*.jar
    title: "[1.18.2] Dev Build"
    prerelease: true
    tag: dev-1.18
    note: CHANGELOG.md
    allow_edit: true
- name: rebuild-cache
  image: meltwater/drone-cache
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: s3id
    AWS_SECRET_ACCESS_KEY:
      from_secret: s3key
  pull: true
  settings:
    rebuild: true
    path-style: true
    bucket:
      from_secret: s3bucket
    region:
      from_secret: s3region
    endpoint:
      from_secret: s3url
    mount:
      - '.gradle'
      - '/root/.gradle'

trigger:
    branch:
    - "1.18.2"
    event:
    - push

---

kind: pipeline
name: tagbuild

steps:
- name: build
  image: gradle:7.4-jdk17
  environment:
    CURSE_TOKEN:
      from_secret: curse_token
    MODRINTH_TOKEN:
      from_secret: modrinth_token
  commands:
  - gradle clean build modrinth curseforge
- name: release
  image: unascribed/drone-gitea-release
  settings:
    api_key:
      from_secret: gitea_key
    base_url: https://git.sleeping.town
    files:
      - build/libs/yttr-*.jar
    title: v${DRONE_TAG}
    tag: "${DRONE_TAG}"
    note: CHANGELOG.md

trigger:
    event:
    - tag
    ref:
      exclude:
      - refs/tags/dev-1.19
      - refs/tags/dev-1.18
      - refs/tags/dev-1.16
