kind: pipeline
name: autobuild

steps:
- name: build
  image: gradle:7.4-jdk17
  commands:
  - gradle clean build
- name: retag
  image: alpine/git:latest
  environment:
    GITEA_KEY:
      from_secret: gitea_key
  commands:
  - "git tag -d dev-1.18 || true"
  - git tag dev-1.18 1.18.2
  - "git push -f https://drone:$GITEA_KEY@git.sleeping.town/unascribed/Yttr.git dev-1.18"
- name: release
  image: unascribed/drone-gitea-release
  settings:
    api_key:
      from_secret: gitea_key
    base_url: https://git.sleeping.town
    files:
      - build/libs/yttr-*.jar
    title: "[1.18.2] Dev Build"
    prerelease: true
    tag: dev-1.18
    note: CHANGELOG.md
    allow_edit: true

trigger:
    branch:
    - "1.18.2"
    event:
    - push

---

kind: pipeline
name: tagbuild

steps:
- name: build
  image: gradle:7.4-jdk17
  environment:
    CURSE_TOKEN:
      from_secret: curse_token
    MODRINTH_TOKEN:
      from_secret: modrinth_token
  commands:
  - gradle clean build modrinth curseforge
- name: release
  image: unascribed/drone-gitea-release
  settings:
    api_key:
      from_secret: gitea_key
    base_url: https://git.sleeping.town
    files:
      - build/libs/yttr-*.jar
    title: v${DRONE_TAG}
    tag: "${DRONE_TAG}"
    note: CHANGELOG.md

trigger:
    event:
    - tag
    ref:
      exclude:
      - refs/tags/dev-1.18
      - refs/tags/dev-1.16

---

kind: pipeline
name: promotetag

steps:
- name: retag
  image: alpine/git:latest
  environment:
    GITEA_KEY:
      from_secret: gitea_key
  commands:
  - git tag dev-1.18 1.18.2
  - "git push https://drone:$GITEA_KEY@git.sleeping.town/unascribed/Yttr.git dev-1.18"

trigger:
    branch:
    - "1.18.2"
    event:
    - push
