name: "Dev Autobuild"

on:
  push:
    branches:
      - trunk
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'mkdocs.yml'
      - 'art-src/**'

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          ./gradlew build
      - name: Delete dev artifact
        run: |
          rm build/libs/*-dev.jar
      - name: Create release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Dev Build"
          files: build/libs/yttr-*.jar
